const Tech = [
    "React.js",
    "Node.js",
    "TypeScript",
    "Docker",
    "Kubernetes",
    "GraphQL",
    "Next.js",
    "Tailwind CSS",
    "Vue.js",
    "Svelte",
    "Python",
    "Django",
    "Flask",
    "FastAPI",
    "JavaScript (ES6+)",
    "HTML5",
    "CSS3",
    "Bootstrap",
    "MongoDB",
    "PostgreSQL",
    "Redis",
    "Elasticsearch",
    "AWS (Amazon Web Services)",
    "Google Cloud Platform (GCP)",
    "Microsoft Azure",
    "Serverless",
    "Machine Learning",
    "Deep Learning",
    "Blockchain",
    "Git",
    "GitHub",
    "GitLab",
    "Jenkins",
    "CI/CD",
    "Agile Methodology",
    "DevOps",
    "Microservices",
    "RESTful APIs",
    "GraphQL APIs",
    "WebAssembly",
    "Rust",
    "Go (Golang)",
    "Kotlin",
    "Swift",
    "Flutter",
    "TensorFlow",
    "PyTorch",
    "Apache Kafka",
    "Apache Spark",
    "Big Data",
    "Data Science",
    "Data Engineering",
    "Cybersecurity",
    "Artificial Intelligence (AI)",
    "Natural Language Processing (NLP)",
    "Robotics",
    "Internet of Things (IoT)",
    "AR/VR (Augmented Reality/Virtual Reality)",
    "UI/UX Design",
    "Responsive Web Design",
    "Progressive Web Apps (PWAs)",
  ];
  Tech.sort();
export default Tech